### - ndarray -



In [3]:
import numpy as np

A = [1, 2, 3]
B = [4, 5, 6]
C = []

print(list(zip(A, B))) 
# [(1, 4), (2, 5), (3, 6)]

for a, b in zip(A, B):
    C.append(a + b)
    
print(C)    



[(1, 4), (2, 5), (3, 6)]
[5, 7, 9]


In [6]:
a = [[1, 2, 3, 4] for _ in range(1000000)]
b = np.array(a)

def exchange_list(a):
    c = []
    for x in a:
        x[2], x[3], x[0], x[1] = x
        c.append(x)      
    return c

def exchange_ndarray(a):
    return a[ : , [2, 3, 0, 1]]
                 
print(a[:2], b[:2], sep='\n')                 

[[1, 2, 3, 4], [1, 2, 3, 4]]
[[1 2 3 4]
 [1 2 3 4]]


## ndarray 생성하기 np.array()

In [7]:
list1 = [1, 2, 3]
print('list1 :',list1)
print('list1 type :',type(list1))

list1 : [1, 2, 3]
list1 type : <class 'list'>


In [8]:
array1 = np.array(list1)
print('array1 :',array1)
print('array1 type :',type(array1))

array1 : [1 2 3]
array1 type : <class 'numpy.ndarray'>


### ndarray 의 shape(형태), dimension(차원)

In [12]:
array1 = np.array([1, 2, 3])
print('array1 type :',type(array1))
print('array1 array 형태 :',array1.shape)

array2 = np.array([[1, 2, 3],
                   [2, 3, 4]])
print('array2 type :',type(array2))
print('array2 array 형태 :',array2.shape)

array3 = np.array([[1, 2, 3]])
print('array3 type :',type(array3))
print('array3 array 형태 :',array3.shape)

array1 type : <class 'numpy.ndarray'>
array1 array 형태 : (3,)
array2 type : <class 'numpy.ndarray'>
array2 array 형태 : (2, 3)
array3 type : <class 'numpy.ndarray'>
array3 array 형태 : (1, 3)


In [13]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.
     format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


* ndarray 데이터 값 타입

In [16]:
list1 = [1, 2, 3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

list2 = [1, 2, 'numpy test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)
'''
['1' '2' 'numpy test'] <U11 : 문자열타입
[1. 2. 3.] float64
'''

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32
['1' '2' 'numpy test'] <U11
[1. 2. 3.] float64


* astype() 사용해서 type 변환하기

In [20]:
array_int = np.array([1, 2, 3])
print(array_int, array_int.dtype)
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float.astype('int32')
print(array_int2, array_int2.dtype)

[1 2 3] int32
[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


* adarray 에서 axix 기반의 연산함수 수행하기

In [26]:
array2 = np.array([[1, 2, 3],
                 [2, 3, 4]])

print(array2.sum())
print(array2.sum(axis=0)) # axis=0 : 행방향 (행끼리 연산)
print(array2.sum(axis=1)) # axis=1 : 열방향 (열끼리 연산)

15
[3 5 7]
[6 9]


* adarray 생성하기 - aragne, zeros, ones

In [27]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype,sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [29]:
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [30]:
one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


* ndarray 의 shape 변경하기 - reshape()

In [37]:
array1 = np.arange(10)
print('array1 :\n',array1)
print('array1 dtype :',array1.dtype)
print('array1 shape :',array1.shape)
print("-------------------------")

array2 = array1.reshape(2, 5)
print('array2 :\n',array2)
print('array2 dtype :',array2.dtype)
print('array2 shape :',array2.shape)

array1 :
 [0 1 2 3 4 5 6 7 8 9]
array1 dtype : int32
array1 shape : (10,)
-------------------------
array2 :
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array2 dtype : int32
array2 shape : (2, 5)


In [38]:
array3 = array1.reshape(5, 2)
print('array3 :\n',array3)
print('array3 dtype :',array3.dtype)
print('array3 shape :',array3.shape)

array3 :
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array3 dtype : int32
array3 shape : (5, 2)


In [40]:
# array1.reshape(4, 3)
# ValueError: cannot reshape array of size 10 into shape (4,3)
# 변환할 수 없는 shape 구조를 입력하면 오류 발생함

* reshape() 에 -1 인자값을 넣으면 
* 특정 차원으로 고정된 가변적인 ndarray 형태 변환

In [44]:
array1 = np.arange(10)
print(array1)

# 컬럼 axis 크기는 5로 고정하고
# 로우 axis 크기를 이에 맞추어 자동으로 변환함 <-  2 X 5
array2 = array1.reshape(-1, 5)
print('array2 shape :',array2.shape)
print('array2 :\n',array2)


# 로우 axis 크기는 5로 고정하고
# 컬럼 axis 크기를 이에 맞추어 자동으로 변환함 <-  5 X 2
array3 = array1.reshape(5, -1)
print('array3 shape :',array3.shape)
print('array3 :\n',array3)

[0 1 2 3 4 5 6 7 8 9]
array2 shape : (2, 5)
array2 :
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 shape : (5, 2)
array3 :
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [46]:
# array3 = array1.reshape(4, -1)
# ValueError: cannot reshape array of size 10 into shape (4,newaxis)
# 변환할 수 없는 shape 구조를 입력하면 오류 발생함

* reshape() 는 (-1, 1), (-1) 과 같은 형태로 주로 사용함
* 1차원 ndarray를 2차원으로
* 또는 2차원 ndarray 를 1차원으로 변환할 때 사용함

In [51]:
array1 = np.arange(5)
print(array1)
print('------------------------')

# 1차원 ndarray를 2차원으로 변환
# 열을 1 열로 고정하면, 행은 5행이 됨 <- 5 X 1
array_1to2 = array1.reshape(-1, 1)
print('array_1to2 shape :',array_1to2.shape)
print('array_1to2 :\n',array_1to2)
print('------------------------')

# 2차원 ndarray를 1차원으로 변환
array_2to1 = array_1to2.reshape(-1,)
print('array_2to1 shape :',array_2to1.shape)
print('array_2to1 :\n',array_2to1)

[0 1 2 3 4]
------------------------
array_1to2 shape : (5, 1)
array_1to2 :
 [[0]
 [1]
 [2]
 [3]
 [4]]
------------------------
array_2to1 shape : (5,)
array_2to1 :
 [0 1 2 3 4]


In [56]:
array1 = np.array(10)
# array4 = array1.reshape(-1, 4)
# ValueError: cannot reshape array of size 1 into shape (4)
# 변환할 수 없는 shape 구조를 입력하면 오류 발생함
# array4 = array1.reshape(-1, -1)
# print('array4 :\n',array4)
# ValueError: can only specify one unknown dimension
# -1은 반드시 하나만 입력해야 함