## ndarray의 data set  선택하기  - indexing
* 특정 위치의 단일값 추출하기

In [8]:
import numpy as np

array1 = np.arange(start=1, stop=10)
print('array1 :',array1)

value = array1[2]
print('value :',value)
print('type(value) :',type(value))

print('맨 마지막 값 :',array1[-1],', 마지막에서 두 번째 값 :',array1[-2])


array1[0] = 9
array1[7] = 0
print('array1 :',array1)





array1 : [1 2 3 4 5 6 7 8 9]
value : 3
type(value) : <class 'numpy.int32'>
맨 마지막 값 : 9 , 마지막에서 두 번째 값 : 8
array1 : [9 2 3 4 5 6 7 0 9]


In [10]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row=0,col=0) index 가 가리키는 값 :', array2d[0,0])
print('(row=0,col=1) index 가 가리키는 값 :', array2d[0,1])
print('(row=1,col=0) index 가 가리키는 값 :', array2d[1,0])
print('(row=1,col=1) index 가 가리키는 값 :', array2d[1,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가 가리키는 값 : 1
(row=0,col=1) index 가 가리키는 값 : 2
(row=1,col=0) index 가 가리키는 값 : 4
(row=1,col=1) index 가 가리키는 값 : 5


* 슬라이싱 (slicing)

In [11]:
array1 = np.arange(start=1, stop=10)
print(array1)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3 4 5 6 7 8 9]
[1 2 3]
<class 'numpy.ndarray'>


In [12]:
array1 = np.arange(start=1, stop=10)
array4 = array1[1:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)



[2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [22]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array2d :\n',array2d)

print('array2d[0:2, 0:2] :\n',array2d[0:2, 0:2])
print('array2d[1:3, 0:3] :\n',array2d[1:3, 0:3])
print('array2d[1:3, :] :\n',array2d[1:3, :])
print('array2d[:, :] :\n',array2d[:, :])
print('array2d[:2, 1:] :\n',array2d[:2, 1:])
print('array2d[:2, 0] :\n',array2d[:2, 0])
print('array2d[0, :2] :\n',array2d[0, :2])
print('array2d[:1, 0] :\n',array2d[:1, 0])
print('array2d[:2, 0] :\n',array2d[:2, 0])
print('array2d[:3, 0] :\n',array2d[:3, 0])
print('array2d[:1, 1] :\n',array2d[:1, 1])
print('array2d[:2, 1] :\n',array2d[:2, 1])
print('array2d[:3, 1] :\n',array2d[:3, 1])
print('array2d[:1, 2] :\n',array2d[:1, 2])
print('array2d[:2, 2] :\n',array2d[:2, 2])
print('array2d[:3, 2] :\n',array2d[:3, 2])

array2d :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] :
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] :
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] :
 [[4 5 6]
 [7 8 9]]
array2d[:, :] :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] :
 [[2 3]
 [5 6]]
array2d[:2, 0] :
 [1 4]
array2d[0, :2] :
 [1 2]
array2d[:1, 0] :
 [1]
array2d[:2, 0] :
 [1 4]
array2d[:3, 0] :
 [1 4 7]
array2d[:1, 1] :
 [2]
array2d[:2, 1] :
 [2 5]
array2d[:3, 1] :
 [2 5 8]
array2d[:1, 2] :
 [3]
array2d[:2, 2] :
 [3 6]
array2d[:3, 2] :
 [3 6 9]


* 팬시 인덱싱 (fancy indexing)
* 리스트나 ndarray(배열) 로 인덱스 집합을 지정하면
* 지정한 위치의 인덱스에 해당하는 ndarray를 반환함
* 

In [34]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print("-----------------")
print(array1d)
print(array1d[[2, 4, 7]])
array1d[[2, 4, 7]] = [3, 5, 8]
print(array1d)
array1d[[2, 4, 7]] = [0, 0, 0]
print(array1d)
print(array1d[[2, 4, 7]])
print("-----------------")


# [1 2 3 4 5 6 7 8 9]
array1d = np.arange(start=1, stop=10)

'''
[[1 2 3]
 [4 5 6]
 [7 8 9]]
'''
array2d = array1d.reshape(3, 3)

print(array2d[[0,1], 2]) # [3 6]

print(array2d[[0,2], 2]) # [3 9]

print(array2d[[1,2], 2]) # [6 9]


print(array2d[[0, 1], 0:2]) 
'''
[[1 2]
 [4 5]]
'''

print(array2d[[0, 1]]) 
'''
[[1 2 3]
 [4 5 6]]
'''
print("------------------------------------")




[[1 2 3]
 [4 5 6]
 [7 8 9]]
-----------------
[1 2 3 4 5 6 7 8 9]
[3 5 8]
[1 2 3 4 5 6 7 8 9]
[1 2 0 4 0 6 7 0 9]
[0 0 0]
-----------------
[3 6]
[3 9]
[6 9]
[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]


In [39]:
array1d = np.arange(start=1, stop=10)
# array1d : [1 2 3 4 5 6 7 8 9]
array2d = array1d.reshape(3, 3)
'''array2d : [[1 2 3]
              [4 5 6]
              [7 8 9]]
''' 
array3 = array2d[[0,1], 2]
print(array3) # [3 6]
# tolist() : ndarray --> list
print(array3.tolist()) # [3, 6]


array4 = array2d[[0,1], 0:2]
print(array4) 
'''
[[1 2]
 [4 5]]
'''
# tolist() : ndarray --> list
print(array4.tolist()) # [[1, 2], [4, 5]]

array5 = array2d[[0,1]]
print(array5)
'''
[[1 2 3]
 [4 5 6]]
'''
print(array5.tolist()) # [[1, 2, 3], [4, 5, 6]]



[3 6]
[3, 6]
[[1 2]
 [4 5]]
[[1, 2], [4, 5]]
[[1 2 3]
 [4 5 6]]
[[1, 2, 3], [4, 5, 6]]


* boolean indexing (불린(불리언) 인덱싱)
* 조건 필터링과 검색을 동시에 할 수 있음 <-- 자주 사용함

In [45]:
array1d = np.arange(start=1, stop=10)
print(array1d) # [1 2 3 4 5 6 7 8 9]

# ndarray 내의 값이 5 보다 큰 ndarray 를 추출하는 경우
result = []

for i in range(0,9):
    if array1d[i] > 5:
        result.append(array1d[i])    
print(result) # [6, 7, 8, 9]

nd_result = np.array(result)
print(nd_result) # [6 7 8 9]

# boolean indexing : 5보다 큰 값 -  filtering
array3 = array1d[array1d > 5]
print(array3)  # [6 7 8 9]
    



[1 2 3 4 5 6 7 8 9]
[6, 7, 8, 9]
[6 7 8 9]
[6 7 8 9]


In [51]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
print(boolean_indexes)

# array1d : [1 2 3 4 5 6 7 8 9]

# 불리언 인덱스로 filtering함
array5 = array1d[boolean_indexes]
print(array5) # [6 7 8 9]

# 일반 인덱스로 filtering함
# 해당 index 번호의 data 만 filtering함
indexes = np.array([5, 6, 7, 8])
array6 = array1d[indexes]
print(array6)


[False False False False False  True  True  True  True]
[6 7 8 9]
[6 7 8 9]
