### 배열의 정렬 - sort(), argsort()

* Numpy sort() 유형
* np.sort() : 원래의 행열은 유지하고 (immutable)
* 원래의 행렬을 정렬해서 그 정렬된 행렬을 생성해서 반환함
* ndarray.sort() : mutable : 원래의 행렬을 정렬함 - 반환값이 None
* np.sort(), ndarray.sort() 모두 오름차순이 기본
* 내림차순으로 정렬하려면 np.sort()[::-1] 과 같이 함
```
        | axis=1 ---> 열방향 정렬
 axis=0 | [[5, 15]
 행방향 ↓ [6, 2]]
```



In [3]:
import numpy as np
A = np.array([(5, 15),(6, 2)])
print(A)
'''
[[ 5 15]
 [ 6  2]]
'''
A_axis0 = np.sort(A, axis=0)
A_axis1 = np.sort(A, axis=1)

print(A_axis0)  # 행(끼리)방향 정렬
'''
[[ 5  2]
 [ 6 15]]
'''
print(A_axis1)  # 열(끼리)방향 정렬
'''
[[ 5 15]
 [ 2  6]]
'''

[[ 5 15]
 [ 6  2]]
[[ 5  2]
 [ 6 15]]
[[ 5 15]
 [ 2  6]]


###  argsort()
* 원래의 행렬 정렬시 정렬된 행렬의 원래의 index를 필요로 할 때
* np.argsort() 를 사용함
* np.argsort() 는 정렬된 행렬의 원래 행렬의 index를 
* ndarray 형(type)[배열]으로 반환함
* -----------------------------------------------------
* [5, 2, 8, 4]  --  [2, 4, 5, 8]  --  1  3  2  0
*  0  1  2  3        1  3  2  0

In [13]:
original_array = np.array([5, 2, 8, 4])
print('np.sort()하기 전 원래의 행렬 :',original_array) # [5 2 8 4]

# np.sort() 로 정렬하기
sort_array1 = np.sort(original_array)
print('정렬된 행렬(np.sort()) :',sort_array1) # [2 4 5 8]
print('---- np.sort() 로 정렬 후 : immutable ----')
print('원래의 행렬 :',original_array)
print('---------------------------------------------------------')

# ndarray.sort() 로 정렬하기
print('original_array.sort()하기 전 원래의 행렬 :',original_array)
sort_array2 = original_array.sort() # return 값이 없음 (None)
print('정렬된 행렬(original_array.sort()) :',sort_array2) # [2 4 5 8]
print('---- ndarray.sort() 로 정렬 후 : mutable ----')
print('원래의 행렬 :',original_array)



np.sort()하기 전 원래의 행렬 : [5 2 8 4]
정렬된 행렬(np.sort()) : [2 4 5 8]
---- np.sort() 로 정렬 후 : immutable ----
원래의 행렬 : [5 2 8 4]
---------------------------------------------------------
original_array.sort()하기 전 원래의 행렬 : [5 2 8 4]
정렬된 행렬(original_array.sort()) : None
---- ndarray.sort() 로 정렬 후 : mutable ----
원래의 행렬 : [2 4 5 8]


* 내림차순 정렬

In [ ]:
sort_array1_descending = np.sort(original_array)[::-1]
print(sort_array1_descending)

* row(행)방향 정렬 : axis=0
* column(열)방향 정렬 : axis=1

In [20]:
array2d = np.array([[8, 13],[6, 1]])
print('행방향(행끼리) 정렬 :\n',np.sort(array2d,axis=0))
print('열방향(열끼리) 정렬 :\n',np.sort(array2d,axis=1))

행방향(행끼리) 정렬 :
 [[ 6  1]
 [ 8 13]]
열방향(열끼리) 정렬 :
 [[ 8 13]
 [ 1  6]]


In [22]:
original_array = np.array([3, 1, 9, 5])
print(np.sort(original_array))

sort_indices = np.argsort(original_array)
print(type(sort_indices))
print('행렬 정렬시 원래 행렬의 인덱스 :', sort_indices)

[1 3 5 9]
<class 'numpy.ndarray'>
행렬 정렬시 원래 행렬의 인덱스 : [1 0 3 2]


In [24]:
original_array = np.array([3, 1, 9, 5])
print(np.sort(original_array)[::-1])  # 내림차순

sort_indices_descending = np.argsort(original_array)[::-1]
print(type(sort_indices_descending))
print('행렬 내림차순 정렬시 원래 행렬의 인덱스 :', sort_indices_descending)

[9 5 3 1]
<class 'numpy.ndarray'>
행렬 내림차순 정렬시 원래 행렬의 인덱스 : [2 3 0 1]


* key-value 형태의 데이터를
* marry=82, paul=92, jeniffer=86, david=99, hose=84 로 만들고
* argsort()를 사용해서 key값을 정렬하기

* score_array 의 정렬된 값에 해당하는 원래의 행렬위치 index를 반환하고
* name_array 에서 name 값 추출하기


In [29]:
name_array = np.array(['mary','paul','jeniffer','david','hose'])
score_array = np.array([82,92,86,99,84])

# score_array 의 정렬된 값에 해당하는 원래의 행렬위치 index를 반환하고
# name_array 에서 name 값 추출하기

sort_indices = np.argsort(score_array)
print('sort_indices : ',sort_indices) #  [0 4 2 1 3]

name_array_sort = name_array[sort_indices]

score_array_sort = score_array[sort_indices]

print(name_array_sort)
print(score_array_sort)




sort_indices :  [0 4 2 1 3]
['mary' 'hose' 'jeniffer' 'paul' 'david']
[82 84 86 92 99]
