### 선형대수 연산 - 행렬 내적 : 행렬곱

* 행렬 내적
* np.dot(A, B)




In [4]:
import numpy as np

A = np.array([[1, 2, 3],[4, 5, 6]])
B = np.array([[7, 8],[9, 10],[11, 12]])

print(A)
print(B)

np.dot(A, B)
'''
[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
array([[ 58,  64],
       [139, 154]])
'''

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


array([[ 58,  64],
       [139, 154]])

* 전치 행렬
* 행과 열을 교환해서 얻어지는 행렬


In [10]:
A = np.array([[1, 2],[3, 4]])
B = np.array([[1, 2],[3, 4], [5, 6]])

print('A :\n',A)
A_t = np.transpose(A)
print('A_t :\n',A_t)
A_t_t = np.transpose(A_t)
print('A_t_t :\n',A_t_t)
print("------------------")

print('B :\n',B)
B_t = np.transpose(B)
print('B_t :\n',B_t)
B_t_t = np.transpose(B_t)
print('B_t_t :\n',B_t_t)
print("------------------")

A :
 [[1 2]
 [3 4]]
A_t :
 [[1 3]
 [2 4]]
A_t_t :
 [[1 2]
 [3 4]]
------------------
B :
 [[1 2]
 [3 4]
 [5 6]]
B_t :
 [[1 3 5]
 [2 4 6]]
B_t_t :
 [[1 2]
 [3 4]
 [5 6]]
------------------
